function Show_Feature_Number()
    feat_name = {'rise time','counts to','counts from','duration',...
            'peak amplitude','average frequency','rms','asl','reverbation frequency',...
            'initial frequency', 'signal strength', 'absolute energy', 'pp1','pp2',...
            'pp3','pp4','centroid frequency','peak frequency','amplitude of peak frequency','num of freq peaks','weighted peak frequency',...
            'total counts','fall time'};
    for i = 1:length(feat_name)
        disp([num2str(i) ' = ' feat_name{i}]);
    end
end

